Code/Larry/django/labs/labs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contactsApp/', include('contactsApp.urls')),
    path('short/', include('url_shortener.urls')),
    path('library/', include('library.urls')),
]

Code/Larry/django/labs/library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
    # /library/
    path('', views.index, name='index'),
    # /library/checkout/
    path('checkout/', views.checkout, name='checkout'),
    # /library/v2/
    path('v2/', views.v2, name='v2'),
    # /library/checkout_v2/
    path('checkout_v2/', views.checkout_v2, name='checkout_v2'),
    # /library/checkin/
    path('checkin/', views.checkin, name='checkin'),
    # /library/v2/1/detail/
    path('v2/detail/<int:book_id>/', views.book_detail, name='book_detail'),
]

Code/Larry/django/labs/library/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(default="add some detail")
    desc_url = models.CharField(default="add a description url", max_length=200)
    image_url = models.CharField(default="https://lar-mo.com/images/lazy_placeholder.gif", max_length=200)
    publish_date = models.DateField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    checked_out = models.BooleanField() # this can be derived from the checkouts

    def __str__(self):
        return self.author.name + ': ' + self.title

    def get_lendee(self):
        # the latest book checkout associated with this books (self.bookcheckout_set, order_by)
        # if the checkin date is null, then it's checked out
        checkout = self.bookcheckout_set.order_by('-checkout_date').first()
        if checkout is None or checkout.checkin_date is not None:
            return ''
        return checkout.name

    def is_checked_out(self):
        checkout = self.bookcheckout_set.order_by('-checkout_date').first()
        if checkout is None or checkout.checkin_date is not None:
            return False
        return True

class BookCheckout(models.Model):
    name = models.CharField(max_length=200)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    checkout_date = models.DateTimeField()
    checkin_date = models.DateTimeField(default=None, blank=True, null=True)

    def __str__(self):
        return self.name + ': ' + self.book.title

Code/Larry/django/labs/library/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone

from .models import Book, Author, BookCheckout

def index(request):
    books = Book.objects.order_by('author', 'publish_date')
    books_sortby_title = Book.objects.filter(checked_out=False).order_by('title')
    context = {'books': books, 'books_sortby_title': books_sortby_title}
    return render(request, 'library/index.html', context)

def v2(request):
    books = Book.objects.order_by('author', 'title')
    books_available = Book.objects.filter(checked_out=False).order_by('title')
    books_notavailable = Book.objects.filter(checked_out=True).order_by('title')
    selected_book = ''
    # lendee = Book.get_lendee(books)
    if request.method == 'GET' and 'book' in request.GET:
        selected_book = request.GET['book']
    context = {
        'books': books,
        'books_available': books_available,
        'books_notavailable': books_notavailable,
        'selected_book': selected_book,
        # 'lendee': lendee,
    }
    return render(request, 'library/v2.html', context)

def checkout(request):
    book_id = request.POST['checkout_select']
    book = Book.objects.get(id=book_id)
    book.checked_out = True
    book.save()
    return HttpResponseRedirect(reverse('library:index'))

def checkout_v2(request):
    lendee = request.POST['lendee']
    book_id = request.POST['checkout_select']
    book = Book.objects.get(id=book_id)
    book.checked_out = True
    book.save()
    book_checkout_details = BookCheckout(name=lendee, book=book, checkout_date=timezone.now())
    book_checkout_details.save()
    return HttpResponseRedirect(reverse('library:v2'))

def checkin(request):
    book_id = request.POST['checkin_select']
    book = Book.objects.get(id=book_id)
    book.checked_out = False
    book.save()
    book_checkout_details = BookCheckout.objects.get(book_id=book.id, checkin_date__isnull=True)
    book_checkout_details.checkin_date = timezone.now()
    book_checkout_details.save()
    return HttpResponseRedirect(reverse('library:v2'))

def book_detail(request, book_id):
    books_details = Book.objects.get(id=book_id)
    book_checkout_details = BookCheckout.objects.filter(book_id=book_id).order_by('checkin_date')
    context = {
        'title': books_details.title,
        'author': books_details.author,
        'pub_date': books_details.publish_date,
        'desc': books_details.description,
        'desc_url': books_details.desc_url,
        'img_url': books_details.image_url,
        'book_checkout_details': book_checkout_details,
    }
    return render(request, 'library/book_detail.html', context)
    # return HttpResponse('ok')

Code/Larry/django/labs/library/templates/library/book_detail.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}} - Library App</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style media="screen" type="text/css">
      html, body {
        box-sizing: border-box;
        height: 100%;
        margin: 0;
        min-height: 100%;
        padding: 0;
        width: 100%;
      }
      #container {
        background-color: rgba(10, 10, 100, 0.4);
        height: 100%;
        width: 100%;
        display: flex;
        align-items: center;
        flex-direction: column;
        justify-content: flex-start;
      }
      #wrapper {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
      }
      h1 {
        text-align: center;
      }
      h4 {
        text-transform: lowercase;
        font-variant-caps: all-small-caps;
      }
      table {
        border: 1px solid #333;
        background-color: #fff;
        width: 1100px;
      }
      th {
        background-color: rgba(10, 10, 100, 0.2);
        padding: 10px;
        /* border: 1px solid #333; */
      }
      #checkout_details tr:nth-child(2n+1) {
        background-color: rgba(0, 0, 0, 0.1);
      }
      td {
        text-align: center;
        /* border: 1px solid #333; */
      }
      .desc {
        padding: 30px;
        text-align: justify;
      }
      img {
        float: left;
        overflow: auto;
        margin: 0 20px 30px 0;
        border: 1px solid #999;
      }
      #checkout_details {
        padding: 15px;
      }
      #checkout_details > table {
        width: 640px;
      }
      #nav {
        position: relative;
        text-align: left;
        width: 1095px;
        margin: 20px auto 10px;
      }
    </style>
  </head>
  <body>
    <div id="container">
      <div id="nav"><a href="{% url 'library:v2' %}"><b>Home</b></a> &gt; Book Detail</div>
      <table>
        <tr>
          <td><h1>{{title}}</h1></td>
        </tr>
        <tr>
          <th align="center"><h4>author: {{author}} || published on: {{pub_date}}</h4></th>
        </tr>
        <tr>
          <td ><p class="desc"><img src="{{img_url}}">"{{desc}}" <nobr>(Google Books: <a href="{{desc_url}}" target="_blank"><i>source</i></a>)</nobr></p></td>
        </tr>
      </table>
      <div id="checkout_details">
        <h1>Checkout History</h1>
        {% if book_checkout_details %}
        <table>
          <tr>
            <th>Lendee</th>
            <th>Checked Out</th>
            <th>Checked In</th>
          </tr>
          {% for details in book_checkout_details %}
            <tr>
              <td>{{details.name}}</td>
              <td>{{details.checkout_date}}</td>
              {% if details.checkin_date == None %}
                <td><i><a href="{% url 'library:v2' %}?book={{details.book.id}}">N/A</a></i></td>
              {% else %}
                <td>{{details.checkin_date}}</td>
              {% endif %}
            </tr>
          {% endfor %}
        </table>
        {% else %}
          <h4>This are no checkout records for this book.</h4>
        {% endif %}
      </div>
    </div> <!-- end of 'container'-->
  </body>
</html>

Code/Larry/django/labs/library/templates/library/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library App</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style media="screen" type="text/css">
      html, body {
        box-sizing: border-box;
        height: 100%;
        margin: 0;
        min-height: 100%;
        padding: 0;
        width: 100%;
      }
      #container {
        background-color: rgba(10, 10, 100, 0.4);
        height: 100%;
        width: 100%;
        display: flex;
        align-items: center;
        flex-direction: column;
        justify-content: flex-start;
      }
      h1 {
        text-align: center;
      }
      table, tr, th, td {
        border: 1px solid #333;
      }
      th, td {
        padding: 10px;
      }
      th {
        background-color: rgba(10, 10, 100, 0.2);
      }
      select, option {
        padding: 10px;
        font-size: 1.25em;
      }
      #spacer {
        margin-top: 25px;
      }
      #checkout_form {
        display: flex;
      }
      #checkout_form > * {
        padding: 1  5px;
        margin: 5px;
      }
      #checkout_books > * {
        margin: 10px;
      }
    </style>
  </head>
  <body>
    <div id="container">
      <div id="book_list">
        <h1>Books</h1>
        {% if books %}
          <table>
            <tr align="left">
              <th>Title</th>
              <th>Author</th>
              <th>Publish Date</th>
              <th>Checked out?</th>
            </tr>
            {% for book in books %}
            <tr>
              <td>{{book.title}}</td>
              <td>{{book.author}}</td>
              <td>{{book.publish_date|date:"F d, Y"}}</td>
              {% if book.checked_out %}
                <td>Yes</td>
              {% else %}
                <td>No</td>
              {% endif %}
            </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>No books are available.</p>
        {% endif %}
      </div> <!-- end of 'book_list' -->
      <div id="spacer">***</div>
      <div id="checkout_books">
        {% if books_sortby_title %}
          <form action="{% url 'library:checkout' %}" method="post" id="checkout_form">
            {% csrf_token %}
            <h2><u>Front Desk</u>:</h2>
            <select name="checkout_select" required>
              <option value="" disabled selected>Select one of these books...</option>
              {% for book in books_sortby_title %}
              <option value="{{book.id}}">{{book.title}}</option>
              {% endfor %}
            </select>
            <button type="submit" class="w3-button w3-black w3-round-large">Checkout</button>
          </form>
        {% else %}
          <h4>There are currently no books to checkout. Try back later.</h4>
        {% endif %}
      </div> <!-- end of 'checkout_books' -->
    </div> <!-- end of 'container'-->
  </body>
</html>

Code/Larry/django/labs/library/templates/library/v2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library App</title>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <style media="screen" type="text/css">
      html, body {
        box-sizing: border-box;
        height: 100%;
        margin: 0;
        min-height: 100%;
        padding: 0;
        width: 100%;
      }
      #container {
        background-color: rgba(10, 10, 100, 0.4);
        height: 100%;
        width: 100%;
        display: flex;
        align-items: center;
        flex-direction: column;
        justify-content: flex-start;
      }
      #wrapper {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
      }
      h1 {
        text-align: center;
      }
      table, tr, #wrapper {
        border: 1px solid #333;
        background-color: #fff;
      }
      th, td {
        padding: 10px;
      }
      th {
        background-color: rgba(10, 10, 100, 0.2);
      }
      select, option {
        padding: 10px;
        font-size: 0.9em;
      }
      #spacer {
        margin-top: 25px;
        height: 30px;
      }
      #checkout_form, #checkin_form {
        display: flex;
      }
      #checkout_form > *, #checkin_form > * {
        padding: 1 5px;
        margin: 5px;
      }
      #checkout_books > *, #checkin_books > * {
        margin: 10px;
      }
    </style>
  </head>
  <body>
    <div id="container">
      <div id="book_list">
        <h1>Books</h1>
        {% if books %}
          <table>
            <tr align="left">
              <th>Title</th>
              <th>Author</th>
              <th align="center">Year Published</th>
              <th align="center">Available?</th>
              <th>Lendee</th>
            </tr>
            {% for book in books %}
            <tr>
              <td><a href="detail/{{book.id}}/">{{book.title}}</a></td>
              <td>{{book.author}}</td>
              <td align="center">{{book.publish_date|date:"Y"}}</td>
              {% if book.checked_out %}
                <td align="center">No</td>
              {% else %}
                <td align="center"><u>Yes</u></td>
              {% endif %}
              <td>{{book.get_lendee}}</td>
            </tr>
            {% endfor %}
          </table>
        {% else %}
          <p>No books are available.</p>
        {% endif %}
      </div> <!-- end of 'book_list' -->
      <div id="spacer"></div>
      <h1>Front Desk</h1>
      <div id="wrapper">
        <div id="checkout_books">
          {% if books_available %}
            <form action="{% url 'library:checkout_v2' %}" method="post" id="checkout_form">
            {% csrf_token %}
              <h2><u>Check-out</u>:</h2>
              <input type="text" placeholder=" enter your name" name="lendee" class="w3-round-large w3-pale-green" required/>
              <select name="checkout_select" required class="w3-pale-green">
                <option value="" disabled selected>Select one of these books...</option>
                {% for book in books_available %}
                <option value="{{book.id}}">{{book.title}}</option>
                {% endfor %}
              </select>
              <button type="submit" class="w3-button w3-black w3-round-large">Save</button>
            </form>
          {% else %}
            <h4>There are currently no books to checkout. Try back later.</h4>
          {% endif %}
        </div> <!-- end of 'checkout_books' -->
        <div id="checkin_books">
          {% if books_notavailable %}
            <form action="{% url 'library:checkin' %}" method="post" id="checkin_form">
            {% csrf_token %}
              <h2>&nbsp;&nbsp;<u>Check-in</u>:</h2>
              <select id="checkin_select" name="checkin_select" required class="w3-pale-green">
                <option value="" disabled selected>Select one of these books...</option>
                {% for book in books_notavailable %}
                <option value="{{book.id}}">{{book.title}}</option>
                {% endfor %}
              </select>
              <button type="submit" class="w3-button w3-black w3-round-large">Save</button>
            </form>
          {% else %}
            <h2><u>Check-in</u>: All books are checked in.</h2>
          {% endif %}
        </div> <!-- end of 'checkin_books' -->
      </div> <!-- end of 'wrapper' -->
    </div> <!-- end of 'container'-->
    <script type="text/javascript">
      checkin_select = document.querySelector('#checkin_select')
      // console.log('{{selected_book}}')
        // if ({{selected_book}} != NULL) {
          checkin_select.value = "{{selected_book}}"
        // }
    </script>
  </body>
</html>