Code/matthew/html/matthew/django/mysite/contacts2/urls.py
from django.urls import path

from . import views

app_name = 'contacts2'
urlpatterns = [
    path('', views.ContactListView.as_view(), name='index'),
    path('create/', views.create_view, name='create'),
    path('<int:contact_id>/', views.edit_view, name='edit'),
]

Code/matthew/html/matthew/django/mysite/contacts2/forms.py
from django.forms import ModelForm
from contacts.models import Contact, Gender, EyeColor

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = []

Code/matthew/html/matthew/django/mysite/contacts2/views.py
from django.shortcuts import render, reverse
from django.views import generic
from contacts.models import Contact, Gender, EyeColor
from .forms import ContactForm
from django.http import HttpResponseRedirect


class ContactListView(generic.ListView):
    model = Contact
    template_name = 'contacts2/contact_list.html'


def create_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        form.save()
        return HttpResponseRedirect(reverse('contacts2:index'))
    else:
        form = ContactForm()
    return render(request, 'contacts2/create.html', {'form': form})


def edit_view(request, contact_id):
    contact = Contact.objects.get(pk=contact_id)
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        form.save()
    form = ContactForm(instance=contact)
    return render(request, 'contacts2/edit.html', {'form': form})

Code/matthew/html/matthew/django/mysite/contacts2/templates/contacts2/contact_list.html
<a href="{% url 'contacts2:create' %}">Create New</a><br/><br/>
{% for contact in contact_list %}
<a href="{% url 'contacts2:edit' contact.id %}">{{contact.name}}</a><br/>
{% endfor %}

Code/matthew/html/matthew/django/mysite/contacts2/templates/contacts2/create.html
<style>
  table * {
    margin:10px;
  }
</style>
<form action="{% url 'contacts2:create' %}" method="post">
  {% csrf_token %}
  <table>
  {{form}}
  </table>
  <button type="submit">save</button>
</form>

Code/matthew/html/matthew/django/mysite/contacts2/templates/contacts2/edit.html
<form action="{% url 'contacts2:edit' form.instance.id %}" method="post">
  {% csrf_token %}
  <table>
  {{form}}
  </table>
  <button type="submit">save</button>
</form>